include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    argument_type_not_assignable: false
    avoid_dynamic_calls: false
    unnecessary_await_in_return: false
    lines_longer_than_80_chars: false
    deprecated_member_use_from_same_package: false
    unnecessary_to_list_in_spreads: false
    deprecated_member_use: false
    cast_nullable_to_non_nullable: false
    parameter_assignments: false
    inference_failure_on_untyped_parameter: false
    use_build_context_synchronously: false

analyzer:
  plugins:
    - very_good_analysis
    - dart_code_metrics
  errors:
    deprecated_member_use_from_same_package: ignore
    
dart_code_metrics:
  metrics-exlude:
    - test/**
    - lib/src/generated/**
    - lib/src/generated_plugin_registrant.dart
    